name: info_space_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  equatable: 2.0.5
  dartz: ^0.10.0
  connectivity_plus: 6.1.0
  flutter_map: 7.0.2
  info_space_repository:
    path: packages/info_space_repository
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: 1.0.4


flutter:
  assets:
    - assets/images/
  uses-material-design: true
